
pipeline {
    agent any
    tools {nodejs "nodejs"}
    stages {
        stage ('Workspace Clean') {
            steps {
             cleanWs()   
            }
        }
        stage ('git clone') {
            steps {
                sh  """
                    echo ${WORKSPACE}
                    git clone https://github.com/sungminlee-angel/exam-node.js-frontend.git
                    """
            }
        }
        stage ('npm build') {
            steps {
                sh  """

                    cd exam-node.js-frontend
                    # npm cache clean --force
                    # npm config delete proxy
                    # npm config delete https-proxy
                    npm install
                    # npm fund
                    # npm audit fix --force
                    CI=false npm run build
                
                    """
            }
        }
        stage ('Ansible Deploy') {
            steps {
                script {

                    MY_KEYPAIR_NAME = ""
                    MY_APP_PRIVATE_IP = "" 

                    sh  """
                        git clone https://github.com/sungminlee-angel/exam-ansible.git
                        cd  exam-ansible 

                        sed -i 's/MY_KEYPAIR_NAME/${MY_KEYPAIR_NAME}/g' hosts/hosts
                        sed -i 's/MY_APP_PRIVATE_IP/${MY_APP_PRIVATE_IP}/g' hosts/hosts

                        ansible-playbook deploy_frontend.yml -i ./hosts/hosts --extra-vars "deploy_hosts=app" 
                        """
                }
            }
        }
    }
}



